### ISSUE TITLE
babel.config.js vs .babelrc

### ISSUE THREAD

**Issue by peterp** [oliviertassinari/i18n-extract#59]
We recently switched to a `babel.config.js` config instead of a `.babelrc.js` config, we're getting the following error:
```
(node:16257) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'end' of undefined
    at CallExpression (/Users/peterp/Chatterbug/chatterbug/node_modules/i18n-extract/lib/extractFromCode.js:166:42)
    at NodePath._call (/Users/peterp/Chatterbug/chatterbug/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/peterp/Chatterbug/chatterbug/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/peterp/Chatterbug/chatterbug/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/peterp/Chatterbug/chatterbug/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/peterp/Chatterbug/chatterbug/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/peterp/Chatterbug/chatterbug/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/Users/peterp/Chatterbug/chatterbug/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/Users/peterp/Chatterbug/chatterbug/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/Users/peterp/Chatterbug/chatterbug/node_modules/@babel/traverse/lib/context.js:118:16)
(node:16257) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16257) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It seems like our code is no longer transpiled by babel, switching the config back to `.babelrc.js` fixed the problem.

Is there something that I'm misunderstanding that's causing this?

**Comment by mmavko** [comment]
I'm getting the same error in my React Native project where I have `babel.config.js` with the following preset:

```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
};
```

(The parsed file has to contain `import` statements to raise the error)

If I remove the preset the error goes away.

**Comment by peterp** [comment]
This is my hacky fix to deal with this:

in package.json:

```json
/* ... */
"scripts: {
    "i18n:extract": "mv babel.config.js .babelrc.js; yarn babel-node ./bin/extract_i18n.js; mv .babelrc.js babel.config.js"
}

**Comment by prograhammer** [comment]
Same problem. Hacky fix I'm doing in Webpack is something like this as @peterp is suggesting:

```js
const fs = require('fs');
const extractFromFiles = require('i18n-extract').extractFromFiles;

fs.copyFile('babel.config.js', '.babelrc.js', (err) => {
  if (err) throw err;
})
fs.rename('babel.config.js', '_babel.config.js', (err) => {
  if (err) throw err;
})

const keys = extractFromFiles(['src/**/*.js']);
console.log(keys);

fs.rename('_babel.config.js', 'babel.config.js', (err) => {
  if (err) throw err;
})
fs.unlink('.babelrc.js', (err) => {
  if (err) throw err;
})
```

**Comment by prograhammer** [comment]
@peterp gave me a clue that it was not using the babel.config.js file. So I ended up putting together this hacky plugin for Webpack. Assumes you also have a `.babelrc` in your root directory (along with your `babel.config.js`):

```js
const fs = require('fs');
const extractFromFiles = require('i18n-extract').extractFromFiles;

class I18nPlugin {
  apply(compiler) {
    fs.rename('babel.config.js', '_babel.config.js', (err) => {
      if (err) throw err;
    })

    const keys = extractFromFiles(['src/**/*.js']);
    console.log(keys);

    fs.rename('_babel.config.js', 'babel.config.js', (err) => {
      if (err) throw err;
    })
  }
}

module.exports = I18nPlugin;
```
